### ISSUE TITLE
4D-PLS on PanopticNuscenes

### ISSUE THREAD

**Issue by LarsKreuzberg** [MehmetAygun/4D-PLS#10]
Hey, I really like your work! Thanks for sharing.
One question. Have you also trained and evaluated 4D-PLS on Panoptic nuScenes? Or only on SemanticKITTI?
If you have also done it on Panoptic nuScenes, would it be possible to share your code for it? I would be very grateful!

Many thanks in advance!

**Comment by MehmetAygun** [comment]
Hi Lars,
Glad that you find our work interesting! I didn't train our model for nuScenes, but I saw this [paper](https://arxiv.org/abs/2112.05210) reported  4D-PLS numbers on nuScenes, maybe you can contact them.
