### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by niritalkalay** [MehmetAygun/4D-PLS#14]
something regrading the evaluation code does not make sense to me, and I hope you can help me clarify some things.. 

1. I run the evaluation code with prediction = GT,to evaluate GT vs GT,  and I did not get association  = 1 (or 100%) like I expected, which is weird:

 code output:

```
/media/nirit/mugiwara/code/4D-PLS/4D-PLS-master/venv/bin/python /media/nirit/mugiwara/code/4D-PLS/4D-PLS-master/utils/evaluate_4dpanoptic.py --dataset=/media/nirit/mugiwara/datasets/SemanticKitti/ --predictions=/media/nirit/mugiwara/datasets/SemanticKitti/ --data_cfg=/media/nirit/mugiwara/datasets/SemanticKitti/semantic-kitti.yaml --split valid --output=/media/nirit/mugiwara/code/4D-PLS/4D-PLS-master/test/Log_2020-10-06_16-51-05_importance_None_str1_bigpug_4/stitch4 
********************************************************************************
INTERFACE:
Data:  /media/nirit/mugiwara/datasets/SemanticKitti/
Predictions:  /media/nirit/mugiwara/datasets/SemanticKitti/
Split:  valid
Config:  /media/nirit/mugiwara/datasets/SemanticKitti/semantic-kitti.yaml
Limit:  None
Min instance points:  50
Output directory /media/nirit/mugiwara/code/4D-PLS/4D-PLS-master/test/Log_2020-10-06_16-51-05_importance_None_str1_bigpug_4/stitch4
********************************************************************************
Ignoring classes:  [0]
[PANOPTIC4D EVAL] IGNORE:  [0]
[PANOPTIC4D EVAL] INCLUDE:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Evaluating sequences: 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
=== Results ===
LSTQ: 0.828126534143485
S_assoc (LAQ): 0.6857935565525006
Assoc: [0.00 0.90 0.07 0.10 0.31 0.25 0.11 0.18 0.02 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00]
iou: [0.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00
 1.00 1.00 1.00 1.00 1.00 1.00]
things_iou: 1.0
stuff_iou: 1.0
S_cls (LSQ): 1.0

Process finished with exit code 0
```

2. as I understand , the instance label of the data is unique for every class, but not for all classes, 
    this means that i can have an object with instance id =2 for class  'cars', and for this class  i will not find another object with the same instance label =2, but I may find another instance label ==2 in the class of "moving-car", and it will be a different object.

so , in the evaluation code(evaluate_4dpanoptic.py) you first load the instance label like so :

![image](https://github.com/MehmetAygun/4D-PLS/assets/36958906/a47e9b0e-a692-4000-8398-3293a6c5bc3d)

(this means that the label_inst is not unique for all classes)
and then later on , when you use it in the code(eval_np.py) combining with offset:

![image](https://github.com/MehmetAygun/4D-PLS/assets/36958906/707154d8-a101-4d4a-a50a-51066a10f95d)

and here:
![image](https://github.com/MehmetAygun/4D-PLS/assets/36958906/1b00e324-8897-4da8-95cc-0dee7b111002)

we can get the same value (offset * y_inst_in_cl) for both objects of different class with the same instance label
and  if prediction label is the same  as the GT (unique for every classes but not unique for all classes),
then I suspect a problem here, since different objects can receive the same number for the above line

**Comment by MehmetAygun** [comment]
Hi, 

I think your second remark is correct, in the gt labels, two different unique instances might have the same instance id but different class labels.

In Line 321/322 in eval_np.py we have the two lines:
cl_preds = self.preds[seq]
cl_gts = self.gts[seq][cl]

As you can see, ground truth instances are stored per sequence per class order, while predictions are stored only per sequence.  And intersections, cl_intersects in the same way as ground truths (per seq and per class.)

As you said in the last part, you are right if the predictions are written similarly to ground truth it would be problematic, thus when you use labels as a prediction you would get not score of 1.0  

This code assumes that prediction instances have unique ids as the instance assignment is done via a bottom-up approach and one instance might have points which are assigned to different classes. 

Here: https://github.com/MehmetAygun/4D-PLS/blob/1d029ae10f71a4b635fe6976174707986331e9d5/utils/tester.py#L842C20-L842C75 you can see during testing there is a unique id counter for all classes for the sequence. 

I hope it answers your questions, sorry I haven't worked actively on this project for a while, tried to answer from what I can recall.

**Comment by niritalkalay** [comment]
thank you the the fast reply. 
yes, I understand that the evaluation code expect prediction to have a unique ID for all classes, which is  a different format than the GT format.
so if I take the GT as prediction, I must take care of the gt instance so that they will have a unique ID for all class.
to do so , when loading the prediction, I just removed the shifting part ( the ">>16" part) so even though the prediction is indeed the GT, it will have a unique ID over all class (since the MSB  of the 32 label number belongs to the class).
even in such case, I did not receive score of 100% like I would expect at  the association score part, and on some classes the association score was really low. 
perhaps this is not the way to generate a unique ID ?  or that some different normalization happened here, when calculating the score? or that even thought its is GT, as long as there is some  intersection between two (perhaps different objects) then it get inserted into the formula? I just don't understand why the score is not 100%.

**Comment by MehmetAygun** [comment]
Yeah the shift arithmetic bit might be problematic to create unique ids, 

https://github.com/MehmetAygun/4D-PLS/blob/1d029ae10f71a4b635fe6976174707986331e9d5/utils/eval_np.py#L373
this line might be causing overflow and messing up the intersections. 

one way to debug might be printing gt id instances, pred_id instances, then checking  cl_intersects dictionary to see if two instances that shouldn't be associated are there or not?
