### ISSUE TITLE
visualization tools

### ISSUE THREAD

**Issue by xushilin1** [MehmetAygun/4D-PLS#15]
Hi @MehmetAygun @jbehley 

Thank you for sharing your excellent open-source code and the visualization video on your [homepage](https://mehmetaygun.github.io/4DPLS.html).
 I would greatly appreciate it if you could provide instructions on how to generate the visualization video for 4D Panoptic Lidar Segmentation predictions or ground truth.

**Comment by MehmetAygun** [comment]
Hi, @xushilin1  unfortunateley I dont have the code that generates that visualization video.
