### ISSUE TITLE
Inquiry on GPU Memory Requirements for 4D Panoptic Lidar Segmentation Training

### ISSUE THREAD

**Issue by wdlysyn** [MehmetAygun/4D-PLS#16]
Dear @MehmetAygun ,

I hope this message finds you well. I am currently studying your work on the 4D Panoptic Lidar Segmentation project, and I find it extremely insightful and promising for advancements in autonomous driving technologies.

I am particularly interested in understanding the hardware requirements for training the models described in your paper. Could you please provide information on the minimum GPU memory specifications needed for effective training? Specifically, I would like to know the minimum GPU memory capacity required to handle the dataset and the computational demands of your approach.

Thank you for your time and assistance. I look forward to your response.

Best regards,
Deli Wang

**Comment by MehmetAygun** [comment]
Hi Deli,

Sorry for the very late reply,

I used 48GB memory GPUs for the models in the paper, however, you can use 24GB ones also but when you use less GPU memory, it downsamples the point clouds during training which leads to a decrease in performance. 

Best,
Mehmet
