### ISSUE TITLE
Dataloader structure for other datasets

### ISSUE THREAD

**Issue by sandeepnmenon** [MehmetAygun/4D-PLS#2]
@MehmetAygun Really enjoyed reading the paper. Really excited about applying the clustering problem for large point cloud sequences to handle the memory constraint.
I have a lidar dataset that has been calibrated and all point cloud frames are in the world view. Up until now, I have been plainly concatenating the point cloud frames and trying to train/test.
I would like to use the clustering method mentioned in the paper and was looking at the SemanticKitti dataloader to understand. What are the major steps that need be applied to any dataset for application in your backbone.
I see the following
1. Stacking points and features
2. grid_subsampling
3. Randomly drop some points
4. augmentation_transform
5. segmentation_inputs

I did not understand how the dataloader __getitem__ works without using the batch_index.
Any direction to approach this will be really helpful.

Thank you

**Comment by MehmetAygun** [comment]
I used original kp-conv dataloader, the data loading is working as you described.

Instead of batch index, the get_item function uses s_ind, f_ind( sequence, frame) values to select which sequence to load.
