### ISSUE TITLE
Traning schedule and problem when running test_models.py

### ISSUE THREAD

**Issue by zj2001** [MehmetAygun/4D-PLS#5]
Hi, @MehmetAygun , i enjoy this paper and work very much.  However, I run into some difficulties when training and testing the model. 
 Firstly, would you mind telling me your best training schedule? Is your learning shedule like this: 200 epochs with pre_train=True and then 800 epochs with pre_train=False ; learning_rate = 1e-4 and batch_size = 1 ? 
 Secondly, I immediately ran the test_models.py after I got the code and data ready, but it can't exit "the test loop " with the same output in each loop ( Min potential = 0.0 in each test epoch). In particular , the condition "last_min + 1 < new_min" is never met. Could you please teach me why this happened or whether i mad some mistakes?
 I would be grateful if you could provide me with some instruction.

**Comment by MehmetAygun** [comment]
For training I followed that schedule, however if you are using different data, I would suggest doing the pre-training until the segmentation performance reach a good level. 

For the test_loop, are you using different data or SemanticKITTI ? In SemanticKitti, it should give an error and exit when it reaches the last frame. I used a little modified version of original KP-Conv code for data loading, which is a little confusing.

For that part I would suggest you to check if the [ind](https://github.com/MehmetAygun/4D-PLS/blob/e9267659d152bd29526f5be783dd84e826358d91/datasets/SemanticKitti.py#L251)  is chaning or not ? And if it is not changing you can see what is happening [here](https://github.com/MehmetAygun/4D-PLS/blob/e9267659d152bd29526f5be783dd84e826358d91/datasets/SemanticKitti.py#L1007)

**Comment by zj2001** [comment]
Thanks for your answer, i'm using SemanticKITTI and i will check the code you mention.

**Comment by zj2001** [comment]
The ind is changing.
![image](https://user-images.githubusercontent.com/78792404/126763457-6a1c63a2-f077-414f-b22b-cfc80d5bd2f3.png)
However, I only see the break condition "last_min > num_votes" in tester.py. During my testing process, last_min is never updated because the condition  "last_min + 1 < new_min" is never met. Could you please tell me whether this is normal result? In fact , i haven't understood what does last_min , new_min and num_votes mean .

**Comment by MehmetAygun** [comment]
During testing, it is normal and not important that that numbers are not changing as long as it process different frames. You can check this by looking which frame's predictions are saved. 

During training, the datasampler gives each frame a potential value, and use this value to select which frame to use during an iteration for balancing the class distribution of the input point cloud.

**Comment by zj2001** [comment]
Very thanks for your reply, I understand it!


 
---Original---
From: "Mehmet ***@***.***&gt;
Date: 2021/7/23 17:43:19
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MehmetAygun/4D-PLS] Traning schedule and problem when running test_models.py (#5)




 
During testing, it is normal and not important that that numbers are not changing as long as it process different frames. You can check this by looking which frame's predictions are saved.
 
During training, the datasampler gives each frame a potential value, and use this value to select which frame to use during an iteration for balancing the class distribution of the input point cloud.
