### ISSUE TITLE
Questions about merged_points and test_models.py

### ISSUE THREAD

**Issue by zj2001** [MehmetAygun/4D-PLS#6]
Hi,@MehmetAygun i encounter some other questions this time.
1. While reading the code , i find something confusing [Here](https://github.com/MehmetAygun/4D-PLS/blob/master/datasets/SemanticKitti.py#L464). When training, i found that this condition `if f_inc == 0 or (hasattr(self.config, 'stride') and f_inc % self.config.stride == 0):` is only met  when f_inc = 0, which means that the merged points only contain data from one frame while training. Does this mean that you don't merge the time information during training?
2. Because the test process is too slow, I change [here](https://github.com/MehmetAygun/4D-PLS/blob/master/test_models.py#L196) to `config.input_threads`. But i encounter error `IndexError: index 4073 is out of bounds for axis 0 with size 4071` . Does this mean that i must set num_workers = 0 ?
3. What does "epoch" mean during testing ? Does it mean we need sample and take average during testing ? 
4. Is this whole test standard in point cloud segmentation ?
I'd appreciate some help!

**Comment by MehmetAygun** [comment]
Hi,
1)I added stride param for testing, normally for training it should be 1, so during training multiple points should merged from small temporal window. I fixed train script.
2)Yeah you had to set 0 in current setting, or you can re-write the tester and dataloader to be able to work on multi-thread setting.
3)Actually it doesn't mean anything. It just 200 iteration of testing. It doesnt to any averaging etc.
4)I used original Pytorch  implementation of Kp-Conv as it is for data loader and testing, I am not sure about the other implementations.

**Comment by zj2001** [comment]
Thanks! Could you teach me where is the code of small emporal window ? ( Actually, i haven't learned SLAM before, so i don't have a   clear understanding of your 4D Volume Formation.

**Comment by MehmetAygun** [comment]
In dataloader self.config.n_frames control the size of temporal window. f_inc is used to get next frames, merged_frames represent how many frames are putted into 4D volume. When the f_inc is 0 it uses f_ind'th frame then it increases and load next frame points.  [Here](https://github.com/MehmetAygun/4D-PLS/blob/b8963d4ac2bc65acbb42691cb1cec7c89a012f9d/datasets/SemanticKitti.py#L293) the while loop exit if the number of merged frames are same as self.config.n_frames. [Here](https://github.com/MehmetAygun/4D-PLS/blob/b8963d4ac2bc65acbb42691cb1cec7c89a012f9d/datasets/SemanticKitti.py#L340) the next frames projected onto first frame coordinate system using ego-motion (kinda alignment of points into same space).  Hope these explanatations are clarifies your questions.

**Comment by zj2001** [comment]
Thank you very much~~ I will read the code you mention~

**Comment by zj2001** [comment]
Yes ! My original understanding is in line with your explanation. 
During training, self.config.n_frames = 2 and there is no param "stride". When f_inc = 1, you get the new_coordinates by [ego-motion](https://github.com/MehmetAygun/4D-PLS/blob/b8963d4ac2bc65acbb42691cb1cec7c89a012f9d/datasets/SemanticKitti.py#L452). However , you don't append it to the merged_coords because the [condition](https://github.com/MehmetAygun/4D-PLS/blob/b8963d4ac2bc65acbb42691cb1cec7c89a012f9d/datasets/SemanticKitti.py#L464) is not met which means the features transmitted to network don't contain time information, is my understanding right?

**Comment by MehmetAygun** [comment]
Yeah my bad, I actually added that condition after trainings are done, but now I added the parameter to [training script](https://github.com/MehmetAygun/4D-PLS/blob/b8963d4ac2bc65acbb42691cb1cec7c89a012f9d/train_SemanticKitti.py#L273).

**Comment by zj2001** [comment]
OK~Thank you! I understand it now.
